apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gazzettamailreadercron
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: gazzettamailreadercron
            image: efsadsreg.azurecr.io/mailreader
